default: &defaults
  app_id: 354338691422828
  client_id: 368e1738eba0fe36b5b7e3449b3b3c87
  client_secret: c38dac177565af482f83c984e322ff12
  perms: manage_pages
  page_id: lifeteenwellington


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults